[package]
name = "shelv"
version = "0.1.0"
edition = "2021"
description = "Note taking app optimized for capturing phase."

[dependencies]
# eframe = { path = "../../pub-frameworks/contributing/egui/crates/eframe", features = [
#   "wgpu",
#   "persistence",
#   "ron",
# ] }
# egui_extras = { path = "../../pub-frameworks/contributing/egui/crates/egui_extras", features = [
#   "svg",
# ] }

# eframe = { git = "https://github.com/twop/egui", branch = "configurable-window", features = [
#   "wgpu",
#   "persistence",
#   "ron",
# ] }

# egui_extras = { git = "https://github.com/twop/egui", branch = "configurable-window", features = [
#   "svg",
# ] }

eframe = { version = "0.23.0", features = ["wgpu", "persistence", "ron"] }
egui_extras = { version = "0.23.0", features = ["svg"] }
serde = { version = "1.0.197", features = ["derive"] }
ron = "0.8"
global-hotkey = "0.3.0"
image = "0.24.5"
pulldown-cmark = "0.9.3"
syntect = { version = "5.0.0", default-features = false, features = [
    "default-fancy",
] }
smallvec = "1.10.0"
tray-icon = "0.11.2"
egui-phosphor = { version = "0.3.0", features = ["light"] }
# tray-item = "0.7.1"
winit = "0.28.1"
linkify = "0.10.0"
objc2 = "0.3.0-beta.3"
boa_engine = { git = "https://github.com/boa-dev/boa.git", rev = "8d857ab5bd296a69e0ab1a40b6b074ea3bd16128" }
serde_json = "1.0.115"
directories-next = "2.0.0"
hotwatch = "0.5.0"


[package.metadata.bundle]
name = "Shelv"
identifier = "app.shelv"
icon = ["assets/tray-icon.png"]
version = "1.0.0"
resources = ["assets", "images/**/*.png", "secrets/public_key.txt"]
copyright = "Copyright (c) Simon Korzunov 2023. All rights reserved."
category = "Productivity"
short_description = "Note taking app optimized for capturing phase."
long_description = """
Note taking app optimized for capturing phase.
"""
