[workspace]
resolver = "2"
members = ["lib"]

[package]
name = "memento"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.21.0"
hot-lib-reloader = { version = "^0.6", optional = true }
lib = { path = "./lib" }

[features]
default = []
reload = ["dep:hot-lib-reloader"]
