[workspace]
resolver = "2"
members = ["lib"]

[package]
name = "memento"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { git = "https://github.com/twop/egui", branch = "focus-and-window-builder", features = ["wgpu"] }
# eframe = { path = "../../pub-frameworks/contributing/egui/crates/eframe", features = ["persistence", "wgpu"] }
# egui_extras = {version = "0.21.0", features = ["svg"] }
egui_extras = { git = "https://github.com/twop/egui", branch = "focus-and-window-builder", features = ["svg"] }
global-hotkey = "0.1.2"
hot-lib-reloader = { version = "^0.6", optional = true }
image = "0.24.5"
lib = { path = "./lib" }
remove = "0.1.3"
tray-icon = "0.4.3"
# tray-item = "0.7.1"
winit = "0.28.1"

[features]
default = []
reload = ["dep:hot-lib-reloader"]
