[package]
name = "shelv"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { git = "https://github.com/twop/egui", branch = "focus-and-window-builder", features = ["wgpu"] }
egui_extras = { git = "https://github.com/twop/egui", branch = "focus-and-window-builder", features = ["svg"] }
# eframe = { path = "../../pub-frameworks/contributing/egui/crates/eframe", features = ["persistence", "wgpu"] }
# egui_extras = {version = "0.21.0", features = ["svg"] }
global-hotkey = "0.1.2"
hot-lib-reloader = { version = "^0.6", optional = true }
image = "0.24.5"
pulldown-cmark = "0.9.2"
syntect = { version = "5.0.0", default-features = false, features = ["default-fancy"]}
smallvec = "1.10.0"
tray-icon = "0.4.3"
# tray-item = "0.7.1"
winit = "0.28.1"




