name: Rust

on:
  push:
    branches: ["main"]
  # https://github.com/briskmode/shelv/issues/112
  # TODO: Enable after migrating to linux runners rather than mac OS (just to avoid sky-rocketing costs)
  # pull_request:
  #   branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: ⚡ Cargo Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: 🔨 Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: 🔎 Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      # - name: Upload binaries to release
      #   if: github.event_name == 'push'
      #   uses: svenstaro/upload-release-action@v1-release
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: target/release/shelv
      #     asset_name: shelv
      #     tag: build-${{ github.ref }}
      #     overwrite: true
